### ISSUE TITLE
[Feature]: Xline cluster with dns

### ISSUE THREAD

**Issue by liangyuanpeng** [xline-kv/Xline#351]
### Description about the feature

Xline can not working with dns on kubernetes  , Just got the error of `Error: invalid socket address syntax`, here is the yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: xline
  labels:
    app: xline
spec:
  selector:
    app: xline
  ports:
  - name: xline
    port: 2379
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: xline
  labels:
    app: xline
spec:
  selector:
    app: xline
  ports:
  - name: xline
    protocol: TCP
    port: 2379
    targetPort: 2379

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xline
spec:
  serviceName: xline
  replicas: 3
  selector:
    matchLabels:
      app: xline
  template:
    metadata:
      labels:
        app: xline
    spec:
      containers:
      - name: xline
        image: datenlord/xline:v0.4.1
        command:
        - /bin/sh
        - -c
        - xline --name $POD_NAME --members xline-0=xline-0:2379,xline-1=xline-1:2379,xline-2=xline-2:2379 --data-dir /var/lib/xline --storage-engine rocksdb
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 2379
          name: xline
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/xline
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi
```

Remind me if i missed something,Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
